import React, { createContext, useContext } from 'react';
export const LocaleContext = createContext<'ru' | 'en'>('en');
const dictionary: Record<string, string> = {
'Class probabilities':'Вероятности классов','Finish rate':'Доля финишей','Collision rate':'Доля столкновений','Finish / collision rates by generation':'Финиши / столкновения по поколениям','Epoch':'Эпоха','Time':'Время','Loss reduction':'Снижение ошибки',
'Blue, yellow, and purple = the three drivers; green = finished. Green rays show walls; pink lines show nearby rivals. Other heats train separately, with no collisions between heats. The view automatically switches when its three drivers stop; the next generation starts after all 42 finish. Training runs end at':'Синий, жёлтый и фиолетовый — водители; зелёный — финиш. Зелёные лучи показывают стены, розовые линии — соперников. Тройки учатся независимо. Экран переключается на живой заезд; поколение меняется после завершения всех 42 водителей. Лимит заезда:',
'laps or':'кругов или',
'simulated seconds. Car collisions stop both drivers and reduce earned distance points by 30%. Drivers making no forward progress for 5 simulated seconds are stopped. Opponents and starting slots are shuffled each generation. Finishers earn a speed bonus, so evolution keeps improving after cars learn to stay on the road. Lap times use simulated time and do not change at 12× playback.':'секунд симуляции. Столкновение останавливает обоих и снижает оценку дистанции на 30%. Без продвижения 5 секунд водитель выбывает. Соперники и стартовые позиции перемешиваются. За быстрый финиш начисляется бонус. Время круга не зависит от ускорения просмотра.',
'The network uses the previous 6 weeks. Backtest predictions are recursive: hidden actuals are never fed back. After testing, it refits on all history. The shaded band is ± backtest MAE × √forecast week, an illustrative error scale, not a calibrated confidence interval. Curve-only forecasts cannot anticipate staffing or process changes.':'Сеть использует предыдущие 6 недель. Прогноз рекурсивный: скрытые факты не подаются обратно. После проверки сеть дообучается на всей истории. Полоса ± MAE × √недели — ориентир ошибки, а не доверительный интервал. Кривая не учитывает изменения состава команды и процессов.',
'labeled tickets · inputs: space, first-commit repository/source/date, title length. No merge/release dates or durations enter X. raw fields are unavailable.':'тикетов с ответами. Входы: пространство, репозиторий, источник и дата первого коммита, длина заголовка. Даты мержа и релиза не входят в X. Поля raw недоступны.',
'Forecast uses the latest consecutive weeks with measured values (':'Прогноз использует непрерывную последовательность недель с измерениями (',
'available; at least 36 required). Missing values are skipped, not replaced by zero.':'доступно; нужно не менее 36). Пропуски не заменяются нулём.',
'Validation uses a separate test dataset. MAE is the average absolute error in seconds.':'Проверка на отдельной выборке. MAE — средняя абсолютная ошибка в секундах.',
'Validation uses a separate test dataset. MAE is the average absolute error in dollars.':'Проверка на отдельной выборке. MAE — средняя абсолютная ошибка в долларах.',
'Metrics use your training examples. There is no separate validation set in this experiment.':'Метрики рассчитаны на ваших обучающих примерах. Отдельной проверочной выборки нет.',
'Loss uses the 32×32 training image; no separate validation set.':'Ошибка по обучающей картинке 32×32; отдельной проверочной выборки нет.',
'Training uses 1,200 synthetic examples. The miss is evaluated with physics at your selected target, rather than taken from the training loss.':'Обучение на 1200 синтетических примерах. Промах рассчитывается по физическим формулам для выбранной цели.',
'Epochs 1–120: prefix training; 121–240: refit on full history. Generalization is measured by the separate chronological backtest.':'Эпохи 1–120: обучение на начале истории; 121–240: вся история. Качество прогноза проверяется на скрытом хронологическом периоде.',
'First 100 epochs: chronological holdout; next 100: refit on all completed tickets. Estimates are full-stage durations, not remaining time. Validation uses current stored ticket fields, not historical feature snapshots.':'Первые 100 эпох — хронологическая проверка, затем 100 эпох на всех завершённых тикетах. Оценка — полная длительность этапа, не оставшееся время. Признаки взяты из текущих записей, не исторических снимков.',
'10% of positions are held out. Optimal-move agreement accepts every equally good minimax move.':'10% позиций отложено для проверки. Любой равноценный оптимальный ход minimax считается правильным.',
'Train the network to start':'Обучите сеть для начала игры','Train a tiny neural network, then play against it.':'Обучите маленькую сеть и сыграйте против неё.','Generating minimax examples…':'Генерация примеров minimax…','Network ready. Pick a square!':'Сеть готова. Выберите клетку!','Loss change per epoch':'Изменение ошибки по эпохам','Epoch duration':'Длительность эпохи','Accuracy':'Точность','Validation loss':'Ошибка проверки',
'Neural ballistics':'Нейросетевая баллистика','launch':'Запустить','Gravity':'Гравитация','Ideal trajectory':'Идеальная траектория','· target':'· цель','m away /':'м по горизонтали /','m high':'м по высоте','Network:':'Сеть:','m/s · vertical miss at target:':'м/с · промах по высоте:','m':'м','m/s²':'м/с²',
'Digit recognition':'Распознавание цифр','predict':'Распознать','clear':'Очистить','Class':'Класс','Neurons per layer':'Нейронов в слое','clusters':'Кластеры','spiral':'Спираль','examples':'примеров','Two hidden layers with':'Два скрытых слоя по',
'Load time prediction':'Прогноз времени загрузки','Real estate price prediction':'Прогноз стоимости недвижимости','Driving score · distance + finish speed bonus':'Оценка езды · дистанция + скорость финиша','Generation':'Поколение','Waiting for the first generation…':'Ожидание первого поколения…','● Best':'● Лучший','● Population average':'● Среднее популяции','Population heatmap':'Хитмап популяции','Rows = generations; columns = drivers ranked by score. Lighter = better.':'Строки — поколения; столбцы — водители по оценке. Светлее — лучше.',
'Neural racing':'Нейрогонки','race top three':'Гонка трёх лучших','continue evolution':'Продолжить эволюцию','reset':'Сбросить','Watch heat':'Заезд','Speed':'Скорость','Sensors':'Датчики','· alive in view':'· активных на экране','/3 · alive overall':'/3 · активных всего','· current':'· пройдено','laps · record score':'круга · рекорд оценки','· best lap':'· лучший круг',
'Neural image reconstruction':'Реконструкция изображения','sunset':'Закат','checkerboard':'Шахматная доска','Upload image':'Своя картинка','Neurons':'Нейроны','Fourier coordinates':'Координаты Фурье','Original · 32×32':'Оригинал · 32×32','Network · 64×64':'Результат сети · 64×64',
'Invalid team JSON:':'Ошибка JSON команды:','Team T2M forecast':'Прогноз T2M команды','Team':'Команда','Horizon':'Горизонт','weeks':'недель','Hidden':'Скрытые','days':'дней','Weekly metric · days':'Недельная метрика · дни','● Actual':'● Факт','● Backtest':'● Проверка','● Forecast':'● Прогноз','8-week backtest':'Проверка на 8 неделях','MAE · days':'MAE · дни','Micro network':'Микросеть','Last observed week':'Последняя неделя','Last 4-week average':'Среднее за 4 недели','Week':'Неделя','Forecast · days':'Прогноз · дни','Per-ticket estimate ·':'Оценка тикета ·','Ticket':'Тикет','Hidden-period MAE:':'MAE на скрытом периоде:','days · historical-median baseline:':'дней · историческая медиана:','days.':'дней.','Estimated duration:':'Прогноз длительности:','· actual:':'· факт:',
'Mode':'Режим','Weekly curve':'Недельная кривая','Per-ticket estimate':'Оценка тикета','Metric':'Метрика','Quantile':'Квантиль','released tickets · latest week':'выпущенных тикетов · последняя неделя','· N: commit→merge':'· N: коммит→мерж',', merge→release':', мерж→релиз',', total':', всего',
'Neural tic-tac-toe':'Нейросетевые крестики-нолики','new game':'Новая игра','Play as':'Играть за','X · first':'X · первым','O · second':'O · вторым','Optimal moves on held-out positions:':'Оптимальных ходов на отложенных позициях:',
'Training time (ms)':'Время обучения (мс)','Waiting for training…':'Ожидание обучения…','● Training':'● Обучение','● Validation':'● Проверка','Training heatmap':'Хитмап обучения','Time → · darker = lower, lighter = higher. Each row has its own scale; gray = no measurement.':'Время → · темнее — ниже, светлее — выше. У каждой строки своя шкала; серый — нет измерения.','Hover over points or heatmap cells for values.':'Наведите на точки или клетки хитмапа для точных значений.',
'Color classification map':'Карта классов','Draw a function':'Нарисуйте функцию','Choose a class and click to add examples. Shift-click removes nearby points. The background shows learned class probabilities.':'Выберите класс и добавляйте точки кликом. Shift-клик удаляет ближайшие точки. Фон показывает вероятности классов.','Drag to draw y as a function of x. Each horizontal position has one target value. Light is your curve; gold is the network prediction.':'Рисуйте функцию, удерживая кнопку мыши. Для каждого x задаётся одно значение y. Светлая линия — исходная кривая, золотая — прогноз.',
'neurons each. Change the data or layer size and train again to compare. Predictions update every 5 epochs.':'нейронов. Меняйте данные или размер слоёв и сравнивайте после обучения. Прогноз обновляется каждые 5 эпох.',
'A tiny network learns coordinates → RGB from 1,024 pixels. Watch the image emerge during training.':'Маленькая сеть учит преобразование координат в RGB по 1024 пикселям. Наблюдайте проявление картинки.',
'Uploads are center-cropped to a square. Fourier coordinates help learn fine detail. Larger output evaluates intermediate coordinates; it does not recover missing original detail. Updates every 5 epochs.':'Картинка обрезается до квадрата по центру. Координаты Фурье помогают изучать детали. Увеличение вычисляет промежуточные координаты, но не восстанавливает утраченные детали. Обновление каждые 5 эпох.',
'Distance, target height, and gravity → angle and launch speed. A 3 → 32 → 32 → 2 network learns from simulated examples; shots follow physical equations.':'Расстояние, высота цели и гравитация → угол и скорость. Сеть 3 → 32 → 32 → 2 учится на синтетических примерах; полёт рассчитывается по физическим формулам.',
'Gold = neural aim; gray dashed = minimum-speed ideal solution. Constant gravity, no air resistance. Move the target after training: the network recalculates without retraining. Displayed angles and speeds are bounded to 5–85° and 1–60 m/s.':'Золотая линия — прогноз сети; серый пунктир — идеальное решение с минимальной скоростью. Гравитация постоянная, сопротивления воздуха нет. После обучения цель можно двигать без переобучения. Угол ограничен 5–85°, скорость — 1–60 м/с.',
'42 drivers train in 14 independent heats of three. Networks sense walls, speed, and both rivals; they learn steering, braking, and collision avoidance through evolution.':'42 водителя учатся в 14 независимых тройках. Сети видят стены, скорость и соперников; эволюция обучает рулению, торможению и избеганию столкновений.',
'27 inputs → 64 → 32 → 9 move values. Learns from minimax; plays using its own predictions.':'27 входов → 64 → 32 → 9 оценок ходов. Учится на minimax, играет по своим предсказаниям.',
'Move heatmap for the player to move: darker ≈ loss (−1), middle ≈ draw (0), lighter gold ≈ win (+1). Values are estimates, not probabilities.':'Оценки ходов текущего игрока: −1 — поражение, 0 — ничья, +1 — победа. Это оценки исхода, а не вероятности.',
'Validation uses 10% of the examples, excluded from training.':'Для проверки отложено 10% примеров, исключённых из обучения.',
'Ready to train':'Готово к обучению','Training…':'Обучение…','Training complete':'Обучение завершено','train network':'Обучить сеть','stop training':'Остановить','training…':'Обучение…','watch training':'Начать обучение','train image':'Обучить картинку','train aiming':'Обучить прицеливание','Ready to forecast':'Готово к прогнозу','train & forecast':'Обучить и спрогнозировать','stop':'Остановить','Stopped':'Остановлено','Forecast ready':'Прогноз готов','train ticket predictor':'Обучить предиктор тикетов','pause':'Пауза','start / resume':'Начать / продолжить','replay race':'Повторить гонку','retrain network':'Переобучить сеть','Draw!':'Ничья!','You win!':'Вы победили!','Network wins!':'Сеть победила!','Your turn':'Ваш ход','Network is thinking…':'Сеть думает…','Draw a digit':'Нарисуйте цифру','Real MNIST model ready':'Модель MNIST готова','Loading MNIST data...':'Загрузка MNIST…','Loading MNIST model...':'Подготовка модели MNIST…','Training on real MNIST digits...':'Обучение на цифрах MNIST…','sine':'Синус','step':'Ступенька','abs':'Модуль','First commit → merge':'Первый коммит → мерж','Merge → release':'Мерж → релиз','Technical T2M':'Технический T2M','All spaces':'Все пространства',
'The network beats both baselines on this hidden period.':'Сеть точнее обоих базовых прогнозов на скрытом периоде.','A simple baseline matches or beats the network on this hidden period.':'Простой прогноз не хуже сети на скрытом периоде.','Network beats this baseline.':'Сеть точнее базового прогноза.','Baseline matches or beats the network.':'Базовый прогноз не хуже сети.',
};
export function translate(value: string, language: 'ru' | 'en'): string {
  if (language === 'en') return value;
  const text = value.trim();
  const result = dictionary[text] ?? text
    .replace(/Accuracy · higher is better/g, 'Точность · выше — лучше').replace(/ · lower is better/g, ' · ниже — лучше')
    .replace(/Training: epoch /g, 'Обучение: эпоха ').replace(/Epoch /g, 'Эпоха ').replace(/validation accuracy /g, 'точность проверки ')
    .replace(/Predicted: /g, 'Распознано: ').replace(/Confidence: /g, 'Уверенность: ').replace(/Space /g, 'Пространство ')
    .replace(/Training failed\. Try again\./g, 'Ошибка обучения. Попробуйте снова.').replace(/Forecast failed\. Try again\./g, 'Ошибка прогноза. Попробуйте снова.')
    .replace(/Stopped\. Current prediction retained\./g, 'Остановлено. Текущий результат сохранён.').replace(/Data changed\. Train to update the prediction\./g, 'Данные изменены. Обучите сеть заново.')
    .replace(/All spaces combined; choose a space to model one team\./g, 'Все пространства вместе; выберите пространство для одной команды.')
    .replace(/First commit → merge/g, 'Первый коммит → мерж').replace(/Merge → release/g, 'Мерж → релиз').replace(/Technical T2M/g, 'Технический T2M')
    .replace(/Forecast ready/g, 'Прогноз готов').replace(/Backtest: history before hidden weeks/g, 'Проверка: история до скрытых недель').replace(/Refit: all observed weeks/g, 'Дообучение: вся история')
    .replace(/Top-three race has no lap or time limit\. Crashed cars remain obstacles\./g, 'У гонки лучших нет лимита. Разбитые машины остаются препятствиями.')
    .replace(/Leading driver stopped:/g, 'Лидер остановился:').replace(/crashed \/ wrong way/g, 'аварии / неверное направление').replace(/Finished:/g, 'Финиш:').replace(/stuck:/g, 'застряли:').replace(/car collisions:/g, 'столкновения:').replace(/timed out:/g, 'таймаут:')
    .replace(/· add at least 3 points/g, '· добавьте хотя бы 3 точки').replace(/Training: epoch /g, 'Обучение: эпоха ').replace(/, epoch /g, ', эпоха ')
    .replace(/ sec/g, ' с').replace(/ MB/g, ' МБ').replace(/days/g, 'дней').replace(/weeks/g, 'недель').replace(/unknown/g, 'неизвестно')
    .replace(/MAE loss/g, 'Ошибка MAE').replace(/Curve MSE/g, 'MSE кривой').replace(/RGB MSE/g, 'MSE цвета').replace(/Cross-entropy/g, 'Кросс-энтропия').replace(/Move-value MSE/g, 'MSE оценок ходов').replace(/Normalized T2M MSE/g, 'Нормализованная MSE T2M').replace(/Normalized duration MSE/g, 'Нормализованная MSE длительности').replace(/Normalized aiming MSE/g, 'Нормализованная MSE прицеливания');
  return value.replace(text, result);
}
export function Localized({ children }: { children?: React.ReactNode }) {
  const language = useContext(LocaleContext);
  const render = (node: React.ReactNode): React.ReactNode => typeof node === 'string' ? translate(node, language) : Array.isArray(node) ? node.map(render) : node;
  return <>{render(children)}</>;
}

export function useLocale() { return useContext(LocaleContext); }
